swagger: '2.0'
info:
  title: HelloWorldAPI
  x-ibm-name: helloworldapi
  version: 1.0.0
  description: This hello world API
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: "context.message.body.write(\"Hello world from APIC\");\r\ncontext.message.header.set('Content-Type', \"text/plain\");"
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
basePath: /helloworldapi
paths:
  /test:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
securityDefinitions:
  clientSecret:
    type: apiKey
    description: Client Secret
    name: X-IBM-Client-Secret
    in: header
    x-key-type: client_secret
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
    clientSecret: []
schemes:
  - https
